<h2><?php echo $this->translate('Languages') ?></h2>
<?php if (count($this->languages)) : ?>
<ul>
    <?php foreach ($this->languages as $code => $name) : ?>
    <li>
        <?php if ($code == $this->language) : ?><?php echo $this->translate($name) ?>
        <?php else : ?><a href="<?php echo $this->url(array('language' => $code), 'default') ?>"><?php echo $this->translate($name) ?><?php endif ?></a>
    </li>
    <?php endforeach ?>
</ul>
<?php endif ?>