<p><a href="http://github.com/pedrobrazao/frameweb">Frameweb</a> is my basic Zend Framework project. Here I will put all the needed steps to build a full featured web project.</p>
<p>At the milestone, it's desired to have:</p>
<ul>
    <li>Default project structure</li>
    <li>Layout and database support</li>
    <li>Admin module</li>
    <li>Multi-language support</li>
    <li>User management</li>
</ul>

